version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend/logs:/app/logs
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
