apiVersion: v1
kind: Service
metadata:
  name: health-monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 5000
      targetPort: 5000
  selector:
    app: health-monitoring
